// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vveksU_Mp7IxoSrQWTFe7FavPQvXLdE',
    appId: '1:467219201860:web:e286b94fe3a9ec23146111',
    messagingSenderId: '467219201860',
    projectId: 'resolute-32f43',
    authDomain: 'resolute-32f43.firebaseapp.com',
    storageBucket: 'resolute-32f43.firebasestorage.app',
    measurementId: 'G-LY14WES5FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfqhuAVqjTuBJ9vFhc0ztOIVQ-IdMLxH4',
    appId: '1:467219201860:android:8040be1fb51de422146111',
    messagingSenderId: '467219201860',
    projectId: 'resolute-32f43',
    storageBucket: 'resolute-32f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8OtZmQe4tqOT1BsjOUXzMZqh9KcfxLt8',
    appId: '1:467219201860:ios:15f2444cb168bc18146111',
    messagingSenderId: '467219201860',
    projectId: 'resolute-32f43',
    storageBucket: 'resolute-32f43.firebasestorage.app',
    iosBundleId: 'com.novina.resolute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8OtZmQe4tqOT1BsjOUXzMZqh9KcfxLt8',
    appId: '1:467219201860:ios:15f2444cb168bc18146111',
    messagingSenderId: '467219201860',
    projectId: 'resolute-32f43',
    storageBucket: 'resolute-32f43.firebasestorage.app',
    iosBundleId: 'com.novina.resolute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9vveksU_Mp7IxoSrQWTFe7FavPQvXLdE',
    appId: '1:467219201860:web:002ae1f06042f395146111',
    messagingSenderId: '467219201860',
    projectId: 'resolute-32f43',
    authDomain: 'resolute-32f43.firebaseapp.com',
    storageBucket: 'resolute-32f43.firebasestorage.app',
    measurementId: 'G-MJBY0BM2BL',
  );
}
